# 
GET http://0.0.0.0:8070/api/v1/collections/?database=ollama_database-01&tenant=ollama_tenant-01

#
curl http://10.0.0.213:50080/embed/embed 
    -X POST \
    -d '{"inputs":"What is Deep Learning?"}' \
    -H 'Content-Type: application/json'