# Makefile for gopy pkg generation of python bindings to embedding.py
# File is generated by gopy (will not be overwritten though)
# gopy pkg embedding.py

PYTHON=python
PIP=$(PYTHON) -m pip

all: gen

install: install-pkg install-exe

gen:
	gopy pkg -no-make embedding.py

build:
	$(MAKE) -C embedding.py build

install-pkg:
	# this does a local install of the package, building the sdist and then directly installing it
	rm -rf dist build */*.egg-info *.egg-info
	$(PYTHON) setup.py sdist
	$(PIP) install dist/*.tar.gz

install-exe:
	# install executable into /usr/local/bin
	cp embedding.py/pyembedding.py /usr/local/bin/

